### ISSUE TITLE
Failed to launch on startup

### ISSUE THREAD

**Issue by Heizou111** [araten10/EdgewarePlusPlus#120]
Bug description:
When 'launch on startup' is toggled, the config window is unable to save and close. Even when that option is manually toggled in config.json is doesn't launch on startup. 'Timer Mode' can still be toggled and I can still save and close but it still doesn't launch on startup.

OS: Windows 11
Pack link: https://gofile.io/d/p4KJZo
version: 2.4.2_A (versionplusplus: 13b)

 
[config.json](https://github.com/user-attachments/files/18011842/config.json)
[Wed_Dec__4_17-10-22_2024-main.txt](https://github.com/user-attachments/files/18011856/Wed_Dec__4_17-10-22_2024-main.txt)
[Wed_Dec__4_17-10-14_2024-config.txt](https://github.com/user-attachments/files/18011857/Wed_Dec__4_17-10-14_2024-config.txt)

**Comment by Heizou111** [comment]
It also didn't create any shortcut/links in the Windows startup folder like it's supposed to.

**Comment by LewdDevelopment** [comment]
If you run config through `debug.py` and try to enable running on startup and saving, does it output anything? If the output contains your username, you can censor it.

**Comment by Heizou111** [comment]
This portion appeared when I click save

INFO:starting config save write...
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python312\Lib\tkinter\__init__.py", line 1968, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "D:\Game Files\misc\EdgewarePlusPlus-main\EdgewarePlusPlus-main\edgeware\src\config.py", line 706, in <lambda>
    saveExitButton = Button(root, text="Save & Exit", command=lambda: write_save(in_var_group, in_var_names, True))
                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Game Files\misc\EdgewarePlusPlus-main\EdgewarePlusPlus-main\edgeware\src\config.py", line 3567, in write_save
    utils.toggle_run_at_startup(vars["start_on_logon"].get())
  File "D:\Game Files\misc\EdgewarePlusPlus-main\EdgewarePlusPlus-main\edgeware\src\utils\windows.py", line 80, in toggle_run_at_startup
    make_shortcut("Edgeware++", PYW[Process.MAIN], CustomAssets.icon(), startup_path)
  File "D:\Game Files\misc\EdgewarePlusPlus-main\EdgewarePlusPlus-main\edgeware\src\utils\windows.py", line 46, in make_shortcut
    pyw_process = PYW[process]
                  ~~~^^^^^^^^^
KeyError: WindowsPath('D:/Game Files/misc/EdgewarePlusPlus-main/EdgewarePlusPlus-main/edgeware/edgeware.pyw')

**Comment by LewdDevelopment** [comment]
Does the `edgeware.pyw` file exist in the location on the last line? Running the setup script generates it.
