### ISSUE TITLE
crashes when starting in hibernate mode.

### ISSUE THREAD

**Issue by spencershoe** [araten10/EdgewarePlusPlus#53]
Select number: 1
current wallpaper path: C:\Users\Spencer\Documents\aJJqxxq3ddf\its porn\GAMEvr\EdgewarePlusPlus-main\EdgeWare\resource\wallpaper.png
running original hibernate. number of popups estimated between 10 and 20.
Traceback (most recent call last):
  File "C:\Users\Spencer\Documents\aJJqxxq3ddf\its porn\GAMEvr\EdgewarePlusPlus-main\EdgeWare\start.pyw", line 876, in <module>
    main()
  File "C:\Users\Spencer\Documents\aJJqxxq3ddf\its porn\GAMEvr\EdgewarePlusPlus-main\EdgeWare\start.pyw", line 382, in main
    if HIBERNATE_TYPE == "Spaced":
       ^^^^^^^^^^^^^^
NameError: name 'HIBERNATE_TYPE' is not defined
Done

**Comment by ajasnam** [comment]
Maybe related to this error, but no hibernate settings work for me either.
