### ISSUE TITLE
Drive tab functions

### ISSUE THREAD

**Issue by Wombatant1** [araten10/EdgewarePlusPlus#56]
Hey, as far as I know (I believe I've read it somewhere here or on twitter) either drive functions and downloader aren't really priority for you guys but I've encountered some issues with drive functions. Fill drive does work properly, but the slider doesn't change anything. On both top and lowest setting, it filled a single directory to around 1300 pics in a minute, so I believe there is some problem with delay.
The other thing o found out is that replace function isnt working properly too. I have tried to use it few months back (I believe it was version 8 or 9) and didn't notice anything strange, but I'm current version, replace seems to go in circles, replacing every single picture it can find every time it finds a new file, leading to a massive lag and really bad performance.

I'm running it on win10 and this happens on both my own packs and some found in wild. I can provide more info if needed

**Comment by araten10** [comment]
While working on config window cleanup this week, i've noticed mention of a "number of fill threads config option" in the about tab. The option doesn't seem to exist on the user side, but checking out the config debug edit there also exists a MaxFillThreads variable. If fill drive still doesn't change it's rate in the newer versions/post refactor, it might be due to this variable never being changed to a lower value.

Unsure if replace images bug still occurs, haven't had problems with the light testing i've done in a contained environment and also haven't heard anyone else mention it since

**Comment by Wombatant1** [comment]
So, since the rewrite drive fill is working rather good, fill delay seems to work as intended. I'd need to see about image replace function.

One thing that's off is combination of drive fill with hibernate mode. It works similar to audios, as mentioned in #125 - triggers with hibernate start, does one iteration of filling in selected directory, then waits for another hibernate starting. But its kind of different than non-hinermate one. 
While changing the fill delay in hibernate changes speed of filling (images/time), non hibernate fill delay also changes volume (I mean it like delay 250 creates 4 pictures in single directory, while delay 40 makes 20 in single sweep)
It's not very problematic, but I'm kind of curious why it is like that, and which is intended behaviour 

I was wondering if you ever considered adding a feature someone proposed in pull request #136 - to allow drive fill function to fill folders randomly instead of "from top to bottom"

**Comment by Wombatant1** [comment]
Image replace does not start, debbuger returns:

`Traceback (most recent call last):
  File "C:\Users\X\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "C:\Users\X\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\edgeware\src\main.py", line 81, in <lambda>
    Thread(target=lambda: replace_images(root, settings, pack), daemon=True).start()  # Thread for performance reasons
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\edgeware\src\features\drive.py", line 74, in replace_images
    backup.parent.mkdir(parents=True, exist_ok=True)
  File "C:\Users\X\AppData\Local\Programs\Python\Python312\Lib\pathlib.py", line 1311, in mkdir
    os.mkdir(self, mode)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\ProgramData\\edgeware\\data\\backups\\Mon Apr  7 00:37:34 2025'`
