### ISSUE TITLE
libVLC.dll is not traced

### ISSUE THREAD

**Issue by llcgoons** [araten10/EdgewarePlusPlus#82]
FileNotFoundError: Could not find module 'libvlc.dll' (or one of its dependencies). Try using the full path with constructor syntax.

**Comment by ShakingOcean** [comment]
Yeah, same here. CAn't figure out any troubleshooting tactics from the documentation. There are less .py files tahn before. configure.py doesn't seem to work, nor the debugger.

**Comment by LewdDevelopment** [comment]
For the sake of additional information, do you have VLC installed? You don't need it if not, but it may fix your issue in the meantime.

Could you send the full traceback (you can censor your username if it shows up)?

**Comment by llcgoons** [comment]
Traceback (most recent call last):
  File "F:\ZPS\BSC\New folder\EdgewarePlusPlus-main\EdgewarePlusPlus-main\edgeware\src\config.py", line 44, in <module>
    from panic import send_panic
  File "F:\ZPS\BSC\New folder\EdgewarePlusPlus-main\EdgewarePlusPlus-main\edgeware\src\panic.py", line 6, in <module>
    from settings import Settings
  File "F:\ZPS\BSC\New folder\EdgewarePlusPlus-main\EdgewarePlusPlus-main\edgeware\src\settings.py", line 7, in <module>
    import vlc
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\vlc.py", line 220, in <module>
    dll, plugin_path  = find_lib()
                        ^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\vlc.py", line 180, in find_lib
    dll = ctypes.CDLL('.\\' + libname)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\ctypes\__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: Could not find module 'F:\ZPS\BSC\New folder\EdgewarePlusPlus-main\EdgewarePlusPlus-main\edgeware\libvlc.dll' (or one of its dependencies). Try using the full path with constructor syntax.
Done
Select number:

**Comment by LewdDevelopment** [comment]
Thanks! I pushed a potential fix for this, does it work in the newest version?

**Comment by LewdDevelopment** [comment]
I'm going to assume this has been fixed now. If there are still problems, feel free to open another issue.
